In [115]:
import torch
import torch.nn as nn
torch.manual_seed(111)

In [125]:
model = nn.Linear(1, 1, bias=False)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
model.state_dict()

OrderedDict([('weight', tensor([[0.8280]]))])

In [126]:
x = torch.tensor([[3.0]])
y = torch.tensor([[2]])
x, y

(tensor([[3.]]), tensor([[2]]))

In [153]:
y_hat = model(x)
y_hat

tensor([[4.2516]], grad_fn=<MmBackward0>)

In [149]:
loss = -2*(y_hat - y)**2
loss

tensor([[-5.4822]], grad_fn=<MulBackward0>)

In [150]:
optimizer.zero_grad()
loss.backward()

In [151]:
for name, param in model.named_parameters():
    print(name, param)

weight Parameter containing:
tensor([[1.2185]], requires_grad=True)


In [152]:
optimizer.step()

In [142]:
model.state_dict()

OrderedDict([('weight', tensor([[1.0725]]))])